sudo: required
dist: trusty
services:
  - docker
language: go
go:
  - 1.11.2

addons:
  apt:
    update: true

install:
  - make bootstrap
  - make format
script:
  - make check
  - make all-ci
  - make container
after_success:
  - make deploy-image
notifications:
  email:
    recipients:
    - kiran.mova@cloudbyte.com
    - mayank.patel@mayadata.io
branches:
  except:
    - /^*-v[0-9]/
